.TH "ORDERED_LIST" "" "January 1979" ""
.SH "Simple ordered lists"
.SS "One\-item list"
.IP "1." 4
Hello, world!
.IP "" 0
.SS "Three\-item list"
.IP "1." 4
Hello, world!
.IP "2." 4
Item 2
.IP "3." 4
Item 3
.IP "" 0
.SS "Four\-item list with all 1s"
.IP "1." 4
Item 1
.IP "2." 4
Item 2
.IP "3." 4
Item 3
.IP "4." 4
Item 4
.IP "" 0

